/** §C.53 — topic management strings via i18n */
import { t } from '../../i18n';

export const agentTopicManagerStrings = {
  title: '话题',
  searchPlaceholder: '在当前助手的话题中搜索…',
  viewCard: '卡片',
  viewList: '列表',
  loadingMore: t('topicManager.loadingMore'),
  emptyNoTopicsTitle: '还没有话题',
  emptyNoTopicsDesc: '开始新对话，创建第一个话题',
  emptyNoTopicsAction: '开始新对话',
  emptyFilteredTitle: '无匹配话题',
  emptyFilteredDesc: '尝试调整筛选条件',
  emptyFilteredAction: '清空筛选',
  bulkSelected: (count: number) => `已选 ${count} 项`,
  bulkFavorite: '收藏',
  bulkArchive: '归档',
  bulkMove: '移动',
  bulkDelete: '删除',
  bulkCancel: '取消',
  bulkDeleteTitle: '删除话题',
  bulkDeleteConfirm: (count: number) => `确定删除 ${count} 个话题吗？`,
  archiveStaleLabel: '归档 3 个月未活跃话题',
  archiveStaleTitle: '归档过时话题？',
  archiveStaleConfirm: (count: number) => `将 ${count} 个话题标为已完成`,
  archiveStaleConfirmOk: '确认归档',
  archiveStaleNone: '没有可归档的过时话题',
  archiveStaleDone: (count: number) => `已归档 ${count} 个话题`,
  statusAll: '全部',
  statusPending: '待处理',
  statusRunning: '进行中',
  statusCompleted: '已完成',
  timeAll: '全部时间',
  timeToday: '今天',
  timeWeek: '一周',
  timeMonth: '一月',
  sortUpdated: '更新时间',
  sortCreated: '创建时间',
  sortTitle: '标题',
  groupByTime: '按时间',
  groupByProject: '按项目',
  groupNone: '不分组',
  projectEmpty: '无项目',
  colTitle: t('topicManager.colTitle'),
  colProject: t('topicManager.colProject'),
  colStatus: t('topicManager.colStatus'),
  colSource: t('topicManager.colSource'),
  colUpdated: t('topicManager.colUpdated'),
} as const;
