/** CommandMenu 文案 */
export const commandStrings = {
  about: '关于',
  aiModePlaceholder: '向 AI 提问…',
  aiPainting: 'AI 绘画',
  askAgentPlaceholder: (agent: string) => `向 ${agent} 发送消息…`,
  askAI: 'Ask AI',
  askAIHeading: (query: string) => `询问 ${query}`,
  askAIHeadingEmpty: '询问 AI',
  communitySupport: '社区支持',
  contactUs: '联系我们',
  context: {
    agent: '助理',
    general: '全局',
    settings: '设置',
  },
  defaultAgent: '默认助理',
  inboxAgent: '主智能体',
  empty: '无匹配结果',
  footer: {
    open: '打开',
    select: '选择',
  },
  keyboard: {
    ESC: 'ESC',
    Tab: 'Tab',
  },
  mentionHeading: '提及助理',
  navigate: '导航',
  newAgent: '新建助理',
  newAgentTeam: '新建助理团队',
  newLibrary: '新建库',
  newPage: '新建文稿',
  newTopic: '在当前助手中创建新话题',
  routes: {
    agents: '多智能体',
    community: '社区',
    generation: '生成预览',
    history: '历史存档',
    image: '图片',
    memory: '记忆',
    ops: '运营中心',
    page: '文稿',
    resource: '资源',
    scheduling: '调度中心',
    selection: '内容筛选',
    settings: '系统设置',
    video: 'AI 视频',
  },
  search: {
    agent: '助理',
    assistant: '助理',
    chatGroup: '团队',
    communityAgent: '助理',
    file: '文件',
    folder: '文件夹',
    knowledgeBase: '知识库',
    mcp: 'MCP',
    memory: '记忆',
    message: '对话',
    page: '文稿',
    plugin: '技能',
    topic: '话题',
  },
  searchMore: (query: string, typeLabel: string) => `搜索更多「${query}」${typeLabel}`,
  searchPlaceholder: '搜索话题、助理与命令…',
  sendToAgent: (agent: string) => `发送给 ${agent}`,
  settings: '设置',
  starOnGitHub: 'GitHub Star',
  submitIssue: '提交问题',
  theme: '主题',
  themeDark: '深色模式',
  themeLight: '浅色模式',
  themeSystem: '跟随系统',
  themeCurrent: '当前',
  console: {
    openWorkingSidebar: '打开工作面板 · 技能',
    toggleLeftSidebar: '切换左侧栏',
    toggleRightPanel: '切换工作面板',
    toggleZenMode: '切换 Zen 模式',
    agentBuilder: 'Agent 构建器',
    groupBuilder: '新建助理团队',
  },
} as const;
