/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#0cafcf',
        'primary-deep': '#0892ac',
        ink: '#0a0a12',
        'ink-deep': '#050038',
        charcoal: '#2c2a3a',
        canvas: '#ffffff',
        surface: '#f5f5f7',
        'surface-soft': '#fafafb',
        'surface-yellow': '#fff8d6',
        'surface-lavender': '#efedff',
        hairline: '#e4e5e9',
        'hairline-soft': '#eeeef1',
        'hairline-strong': '#c5c6cc',
        'text-ink': '#1f1b36',
        'text-charcoal': '#3b3850',
        'text-slate': '#6a6680',
        'text-steel': '#85819a',
        'text-stone': '#a8a4bc',
        'text-muted': '#c5c2d0',
        'brand-yellow': '#fcdc2a',
        'brand-yellow-deep': '#e5c800',
        'yellow-light': '#fff6cc',
        'yellow-dark': '#5a4e00',
        'brand-coral': '#ff7a59',
        'coral-light': '#ffe2d6',
        'coral-dark': '#7a1f0f',
        'brand-rose': '#ffd5d8',
        'rose-light': '#ffe9eb',
        'brand-teal': '#1aa499',
        'teal-light': '#d1f5f0',
        'moss-dark': '#0f4f4a',
        'brand-orange-light': '#ffd9b3',
        'background-light': '#f7f7f9',
        'background-dark': '#0c1015',
        'surface-dark': '#161a23',
        'surface-dark-lighter': '#1f2530',
        'surface-darker': '#0a0d12',
        'border-dark': '#2a3040',
        'text-secondary': '#90c1cb',
        'accent-success': '#0bb07b',
        'accent-warning': '#f7b500',
        'accent-error': '#ef4444',
        'brand-red': '#ff5c5c',
      },
      fontFamily: {
        display: ['Inter', 'Noto Sans SC', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        body: ['Inter', 'Noto Sans SC', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      borderRadius: {
        '4xl': '1.75rem',
        feature: '2rem',
      },
      boxShadow: {
        subtle: 'rgba(5, 0, 56, 0.04) 0px 1px 2px 0px',
        card: 'rgba(5, 0, 56, 0.06) 0px 4px 12px 0px',
        mockup: 'rgba(5, 0, 56, 0.08) 0px 12px 32px -4px',
        modal: 'rgba(5, 0, 56, 0.12) 0px 16px 48px -8px',
      },
      animation: {
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
};
