/** §C.54 */
export const taskDetailPageStrings = {
  notFoundTitle: '任务不存在',
  notFoundDesc: '该任务可能已被删除或你无权访问。',
  backToTasks: '返回任务列表',
  instruction: '任务说明',
  subtasks: '子任务',
  artifacts: '产物',
  activities: '活动',
  model: '模型',
  assignee: '负责人',
  parent: '父任务',
  loading: '加载任务详情…',
  taskAgentTitle: '任务助理',
  taskAgentHint: '与任务助理对话，澄清需求或调整执行计划。',
  taskAgentMockUser: '把子任务拆成 3 个可并行步骤。',
  taskAgentMockReply: '建议按依赖关系分为准备、执行、验收三阶段（演示）。',
  run: '运行',
  pause: '暂停',
  runStarted: '任务已开始运行',
  runPaused: '任务已暂停',
  openTopicChat: '关联话题',
  topicChatTitle: '任务关联话题',
  topicChatHint: '查看与该任务关联的会话上下文。',
  goToTopic: '打开话题会话',
  artifactPreviewHint: '产物预览',
  properties: '属性',
};
