/** §C.42*` 中文等价 */
export const modelStrings = {
  byModel: '按模型',
  byProvider: '按服务商',
  emptyModel: '暂无模型，前往配置',
  emptyProvider: '未配置服务商，前往设置',
  goToSettings: '前往系统设置',
  searchPlaceholder: '搜索模型…',
  useModelFrom: '选择服务商',
  detail: {
    provider: '服务商',
    connection: '连接',
    models: '模型',
    advanced: '高级配置',
    name: '名称',
    type: '类型',
    status: '状态',
    defaultProvider: '默认服务商',
    host: 'Host',
    apiKey: 'API Key',
    endpoint: '接口路径',
    proxy: '代理',
    proxyOn: '启用',
    proxyOff: '未启用',
    configuredModels: '已配置模型',
    multimodal: '多模态',
    multimodalOn: '已启用',
    multimodalOff: '未启用',
    reasoningEffort: '推理强度',
    providerNotFound: '未在系统设置中找到该服务商',
  },
} as const;
