/** AI Builder 界面文案（写库前校验 = dry-run，仅 UI，API 路径不变） */
export const aiBuilderUi = {
  stepLabel: '写库前校验',
  stepDescription: '预览变更差异、校验风险，不写库',
  pendingValidation: '待校验',
  running: '校验进行中',
  resultPreview: '写库前校验结果',
  runningPreview: '写库前校验进行中',
  retry: '重新校验',
  failed: '写库前校验失败，无法确认写库。',
  notReady: '写库前校验尚未就绪',
  tokenMissing: '校验确认凭证缺失，请重新执行写库前校验',
  blockedErrors: (n: number) => `写库前校验存在 ${n} 个阻塞错误`,
  notPassed: '写库前校验尚未通过，请重新执行写库前校验',
  waitDryRun: '等待写库前校验',
  footerRunning: '写库前校验进行中…',
  statusRunning: '正在执行写库前校验…',
  statusPreparing: '构建计划已生成，正在准备写库前校验…',
  statusFailed: '写库前校验失败',
  statusReady: '写库前校验已就绪，请确认写库。',
  statusReadyHighRisk: '写库前校验已就绪，但包含高风险变更，写库前需要二次确认。',
  statusBlocked: (n: number) => `写库前校验发现 ${n} 个阻塞错误，请先修订。`,
  tokenMissingActive: '校验确认凭证缺失，请重新执行写库前校验。',
  rerunAfterEdit: '计划已手动修订，状态已改为待校验，正在重新执行写库前校验…',
  summary: (changes: number, errors: number) => `写库前校验：${changes} 个变更，${errors} 个错误`,
  diffPreview: (n: number) => `写库前校验 / 变更预览 · ${n} 项变更`,
  noServerToken: '当前写库前校验没有服务端确认凭证，请重新执行校验。',
  contractConfirm: '契约可评审，完成写库前校验后才能写库。',
  skeletonPhase: '写库前校验 · 进行中'
} as const;
