export const paramsStrings = {
  title: '模型参数',
  agentTitle: 'Agent 参数',
  contextCompression: '上下文压缩',
  historyLimit: '历史消息上限',
  autoScroll: '流式时自动滚动',
  streaming: '流式输出',
  followUpChips: '追问建议',
  followUpHint: '全局追问模型未配置，建议项可能为空。',
  inputTemplate: '输入模板',
  inputTemplatePlaceholder: '在每轮用户消息前插入的模板…',
  modelConfig: '模型扩展',
  advanced: '高级参数',
  creativity: '创造力',
  openness: '开放性',
  topicDivergence: '话题发散',
  vocabularyRichness: '词汇丰富度',
  responseLength: '回复长度',
  reasoningEffort: '推理强度',
  reasoningLow: '低',
  reasoningMedium: '中',
  reasoningHigh: '高',
  enableReasoning: '启用推理',
  reasoningBudget: '推理 Token 预算',
  preserveThinking: '保留思考内容',
  disableContextCaching: '禁用上下文缓存',
  textVerbosity: '文本详略',
  thinking: '思考模式',
  thinkingAuto: '自动',
  thinkingEnabled: '启用',
  thinkingDisabled: '禁用',
  contextCompressionDesc: '压缩历史上下文以节省 Token。',
  maxContextWindow: '最大上下文',
} as const;
