/** §C.22 Plus / Portal 文案集中（i18n 过渡） */
export const plusStrings = {
  tooltip: '添加附件与能力',
  addAttachments: '附件',
  upload: '上传文件或图片',
  viewMoreKb: '查看更多',
  memory: '记忆',
  search: '联网搜索',
  searchOff: '关闭',
  searchOffDesc: '不使用联网搜索',
  searchApp: '应用搜索',
  searchAppDesc: '使用 内置搜索服务',
  searchProvider: '模型内置搜索',
  searchProviderDesc: '使用模型提供商内置搜索',
  gateway: 'Gateway 模式',
  tools: '工具与技能',
  skillAuto: '自动',
  skillManual: '手动',
  typo: '格式工具',
  params: '高级参数',
  bindingSearch: '搜索工具、技能或 MCP…',
  bindingTools: '工具',
  bindingSkills: '技能',
  bindingMcp: 'MCP',
  bindingEmpty: '暂无可绑定的工具、技能或 MCP',
  adminBuiltinBadge: '内置',
  adminCategoryBadge: 'Super Admin 内置',
  policyMenu: '技能策略',
  policyPinned: '固定',
  policyAuto: '自动',
  policyConfigure: '配置',
  policyUninstall: '卸载',
} as const;
